title: NewRock Wireless | Premium Electronics
url: "https://50stateswireless-jpg.github.io"
baseurl: "/NewrockWireless-2"

defaults:
  - scope:
      path: "_layouts/default.html"
    values:
      layout: "default"
